// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjEaATaodzzYCuW6lJM4cAIKMz51OZqRA',
    appId: '1:402794500283:web:99990a55ca239c47edd99e',
    messagingSenderId: '402794500283',
    projectId: 'fir-flutter-ec',
    authDomain: 'fir-flutter-ec.firebaseapp.com',
    storageBucket: 'fir-flutter-ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB61MPSnerYlxcqNSzLCeDqY_7bhfZLJ0Y',
    appId: '1:402794500283:android:5927c21988c8bb2eedd99e',
    messagingSenderId: '402794500283',
    projectId: 'fir-flutter-ec',
    storageBucket: 'fir-flutter-ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsyq4YmM91VDohHkMicY1aD1VDl3EgyUw',
    appId: '1:402794500283:ios:3df8fb679f9aafc0edd99e',
    messagingSenderId: '402794500283',
    projectId: 'fir-flutter-ec',
    storageBucket: 'fir-flutter-ec.appspot.com',
    iosBundleId: 'com.example.flutterStoreV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsyq4YmM91VDohHkMicY1aD1VDl3EgyUw',
    appId: '1:402794500283:ios:3df8fb679f9aafc0edd99e',
    messagingSenderId: '402794500283',
    projectId: 'fir-flutter-ec',
    storageBucket: 'fir-flutter-ec.appspot.com',
    iosBundleId: 'com.example.flutterStoreV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjEaATaodzzYCuW6lJM4cAIKMz51OZqRA',
    appId: '1:402794500283:web:9165412c9280c98bedd99e',
    messagingSenderId: '402794500283',
    projectId: 'fir-flutter-ec',
    authDomain: 'fir-flutter-ec.firebaseapp.com',
    storageBucket: 'fir-flutter-ec.appspot.com',
  );
}
